# Generated by Django 5.2.8 on 2025-11-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BALANCE_SHEET', 'Balance Sheet'), ('INCOME_STATEMENT', 'Income Statement'), ('CUSTOM', 'Custom')], max_length=50)),
                ('filters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
